
elasticsearch:
  host: 188.166.136.134
  port: 9200
  user: elastic
  password: ES_PASS
  index: 5tracks


postgres:
  drivername: postgresql
  host: localhost
  port: 5432
  database: discovery
  password:
  username: azymuth

pg_echo: false